import fs from 'fs';
import path from 'path';
import chokidar from 'chokidar';
import prettier from 'prettier';

const INPUT_DIR = './chains';
const OUTPUT_DIR = './src/generated';
const OUTPUT_FILE = `${OUTPUT_DIR}/chains.ts`;

const HEADER_CONTENT = `// ===========================================================================
// DO NOT EDIT THIS FILE MANUALLY!
//
// The contents have been added automatically.
// See: scripts/combine-chains.ts for more information
// ===========================================================================

import { Chain } from '../types';
`;

function mergeJsonFiles() {
  const fileNames = fs.readdirSync(INPUT_DIR);
  const jsonFiles = fileNames.filter((fileName) => fileName.endsWith('.json'));
  const combinedChains: any = [];

  for (const jsonFile of jsonFiles) {
    const filePath = path.join(INPUT_DIR, jsonFile);
    const fileContentRaw = fs.readFileSync(filePath, 'utf-8');
    const fileContent = JSON.parse(fileContentRaw);
    combinedChains.push(fileContent);
  }

  const rawContent = `${HEADER_CONTENT}\nexport const CHAINS: Chain[] = ${JSON.stringify(combinedChains)};\n\n`;
  const formattedContent = prettier.format(rawContent, { parser: 'typescript' });

  if (!fs.existsSync(OUTPUT_DIR)) {
    fs.mkdirSync(OUTPUT_DIR);
  }

  fs.writeFileSync(OUTPUT_FILE, formattedContent);
  console.log(`Combined chains been saved as ${OUTPUT_FILE}`);
}

function watchJsonFiles() {
  const watcher = chokidar.watch([INPUT_DIR], { ignored: /^\./, persistent: true });

  watcher
    .on('add', (path) => {
      console.log(`File ${path} has been added`);
      mergeJsonFiles()
    })
    .on('change', (path) => {
      console.log(`File ${path} has been changed`);
      mergeJsonFiles()
    })
    .on('unlink', (path) => {
      console.log(`File ${path} has been removed`);
      mergeJsonFiles()
    });
}

if (process.argv.includes('--watch')) {
  watchJsonFiles();
} else {
  mergeJsonFiles()
}

