name: Continuous Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  documentation:
    runs-on: ubuntu-latest
    steps:
      - name: Clone @api3/chains
        uses: actions/checkout@v4

      - name: Check hyperlinks
        uses: gaurav-nelson/github-action-markdown-link-check@v1

  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone @api3/chains
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Get yarn cache directory path
        id: deps-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v4
        id: deps-cache
        with:
          path: ${{ steps.deps-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Run Build
        run: yarn build

      - name: Run Linting Checks
        run: yarn lint

      - name: Run Validations
        run: yarn validate

      - name: Run Tests
        run: yarn test

  required-checks-passed:
    name: All required checks passed
    runs-on: ubuntu-latest
    needs: [documentation, lint-test]
    steps:
      - run: exit 0
