name: Trigger on release

on:
  release:
    types: [published]
jobs:
  Trigger:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Repository Dispatch - Release chains
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.PAT }}
        repository: api3dao/update-sentry
        event-type: release
        client-payload: '{"repository": "chains"}'