name: Refresh Block Times

on:
  schedule:
    # Run once a month
    - cron: '0 12 1 * *'

jobs:
  refresh-block-times:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]
        pnpm-version: [8]
    env:
      branchName: action-refresh-block-time
    steps:
      - name: Clone @api3/chains
        uses: actions/checkout@v4

      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - uses: pnpm/action-setup@v3
        name: Install pnpm ${{ matrix.pnpm-version }}
        with:
          version: ${{ matrix.pnpm-version }}
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run providers:time
        run: |
          pnpm providers:time
          pnpm generate:chains

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com>"
          git checkout -b ${{ env.branchName }}
          git commit -am "Refresh block times"
          git push origin HEAD

      - name: Create pull request
        run: gh pr create -B main -H ${{ env.branchName }} --title 'Refresh Block Times' --body 'Created by GitGub Action'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
