# https://github.com/changesets/action
name: Release

on:
  push:
    branches:
      - production

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      packages: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build package
        run: yarn package:build

      - name: Ensure main is present for commit message prep
        run: |
          git checkout main
          git checkout production

      - name: Prep commit message
        run: |
          echo "NEW_VERSION=$(yarn changeset status --output=release.json > /dev/null && jq -r '.releases[0].newVersion' release.json && rm release.json)" >> "$GITHUB_ENV"

      - name: Check release
        id: changesets
        uses: changesets/action@v1
        with:
          publish: yarn release
          commit: 'ci: release chains v${{ env.NEW_VERSION }}'
          title: 'ci: release chains v${{ env.NEW_VERSION }}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create pull request
        if: steps.changesets.outputs.published == 'true'
        run: gh pr create -B main -H production --title 'Merge production into main' --body 'Merges production into main' --reviewer hiletmis
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}